import React, { useMemo } from 'react';
import Month from './Month';
import { Holiday, SchoolHoliday } from '../types';
import { getDaysInMonth, formatDate, isDateInRange } from '../utils/dateUtils';

interface CalendarProps {
  year: number;
  publicHolidays: Holiday[];
  schoolHolidays: SchoolHoliday[];
  loading: boolean;
  countryName: string;
}

const Calendar: React.FC<CalendarProps> = ({ year, publicHolidays, schoolHolidays, loading, countryName }) => {
  // Render 12 months
  const months = Array.from({ length: 12 }, (_, i) => i);

  // Calculate counts for the legend
  const { publicHolidayCount, schoolHolidayCount } = useMemo(() => {
    let pCount = 0;
    let sCount = 0;

    for (let m = 0; m < 12; m++) {
      const days = getDaysInMonth(year, m);
      for (const date of days) {
        const dateStr = formatDate(date);
        const isPublic = publicHolidays.some(h => h.date === dateStr);
        
        if (isPublic) {
          pCount++;
        } else {
          // Only check school holiday if not public, because public takes precedence visually
          const isSchool = schoolHolidays.some(h => isDateInRange(dateStr, h.startDate, h.endDate));
          
          // Exclude weekends (0=Sunday, 6=Saturday) from the count
          const isWeekend = date.getDay() === 0 || date.getDay() === 6;

          if (isSchool && !isWeekend) {
            sCount++;
          }
        }
      }
    }
    return { publicHolidayCount: pCount, schoolHolidayCount: sCount };
  }, [year, publicHolidays, schoolHolidays]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[600px] bg-white rounded-lg shadow-sm border border-slate-200">
        <div className="w-12 h-12 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin mb-4"></div>
        <p className="text-slate-500">Generating Calendar...</p>
      </div>
    );
  }

  return (
    <div className="w-full bg-white print:bg-white p-4 print:p-0 mx-auto max-w-[1200px]">
      {/* Title Header */}
      <div className="text-center mb-6 print:mb-4">
        <h1 className="text-5xl font-serif font-bold text-slate-900 mb-2">{year}</h1>
        <p className="text-sm text-slate-500 print:text-slate-600 uppercase tracking-widest">
           {countryName} • School Holidays Highlighted
        </p>
      </div>

      {/* Grid Layout: 3 Columns x 4 Rows */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 print:grid-cols-3 print:gap-4 print:text-xs">
        {months.map((monthIndex) => (
          <Month
            key={monthIndex}
            year={year}
            monthIndex={monthIndex}
            publicHolidays={publicHolidays}
            schoolHolidays={schoolHolidays}
          />
        ))}
      </div>

      {/* Footer / Legend */}
      <div className="mt-8 pt-4 border-t border-slate-200 print:mt-4 print:pt-2">
        <div className="flex flex-wrap gap-1 mb-4 print:mb-2 text-sm font-medium">
           <div className="flex items-center border border-slate-300 bg-[#89d6e8] px-4 py-1.5 w-1/3 justify-center text-center">
             School Holiday ({schoolHolidayCount} days)
           </div>
           {/* Private School would be manual, not implemented in auto-fetch logic, leaving out or adding placeholder */}
           <div className="flex items-center border border-slate-300 bg-[#ffcc00] px-4 py-1.5 flex-1 justify-center text-center">
             Public Holiday ({publicHolidayCount} days)
           </div>
        </div>

        <div className="grid grid-cols-[120px_1fr] gap-x-4 gap-y-1 text-xs text-slate-700 print:text-[10px]">
          <div className="font-bold">Public Holidays:</div>
          <div className="truncate text-blue-600 underline">https://www.gov.uk/bank-holidays</div>
          
          <div className="font-bold">School Holidays:</div>
          <div className="truncate text-blue-600 underline">https://www.gov.uk/school-term-holiday-dates</div>

          <div className="col-span-2 mt-2 text-slate-400 italic">
            Generated by UK Holiday Calendar App. Check local council websites for exact school term variations.
          </div>
        </div>
      </div>
    </div>
  );
};

export default Calendar;